# -*- coding: utf-8 -*-
"""1BM23AI097_DAV_lab7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A3xsq-Nu1-mVw96ZbzNSgmR3nf7Drfrw
"""



from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('/content/drive/MyDrive/uber-raw-data-aug14.csv')
df['Date/Time'] = pd.to_datetime(df['Date/Time'])
df['DayOfWeek'] = df['Date/Time'].dt.day_name()
df['Hour'] = df['Date/Time'].dt.hour
days_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'friday', 'Saturday', 'Sunday']

heatmap_data = df.pivot_table(index = 'DayOfWeek', columns = 'Hour', values='Date/Time', aggfunc='count')
heatmap_data = heatmap_data.reindex(days_order)
plt.figure(figsize=(12, 6))
sns.heatmap(heatmap_data, cmap = 'YlOrRd', linewidths = 0.5)
plt.title('Uber Pickups by Dat Of Week and Hour OF Day',fontsize=16)
plt.xlabel('Hour of Day')
plt.ylabel('Day of Week')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt


df = pd.read_csv('/content/drive/MyDrive/uber-raw-data-aug14.csv')


df['Date/Time'] = pd.to_datetime(df['Date/Time'])


df['Date'] = df['Date/Time'].dt.date


daily_pickups = df.groupby('Date').size()


plt.figure(figsize=(12, 6))
plt.plot(daily_pickups.index, daily_pickups.values, marker='o',
linestyle='-', color='teal')


plt.title('Trend of Uber Pickups in April 2014', fontsize=16)
plt.xlabel('Date')
plt.ylabel('Number of Pickups')
plt.grid(True)
plt.tight_layout()

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('/content/drive/MyDrive/uber-raw-data-aug14.csv')
df['Date/Time'] = pd.to_datetime(df['Date/Time'])

def classify_region(lat, lon):
  if 40.70 <= lat <= 40.85 and -74.02 <= lon <= -73.93:
    return 'Manhattan'
  elif 40.57 <= lat <=40.74 and -74.05 <= lon <= -73.85:
    return 'Brooklyn'
  elif 40.84 <= lat <= 40.91 and -73.92 <= lon <= -73.77:
    return 'Bronx'
  elif 40.64 <= lat <= 40.79 and -73.87 <= lon <= -73.73:
    return 'Queens'
  elif 40.50 <= lat <= 40.65 and -74.25 <= lon <= -74.05:
    return 'Staten Island'
  else:
    return 'Other'


df['Region'] = df.apply(lambda row: classify_region(row['Lat'],
row['Lon']), axis=1)


region_pickups = df['Region'].value_counts().reset_index()
region_pickups.columns = ['Region', 'Pickups']

region_coords = {
    'Manhattan': (40.78, -73.97),
    'Brooklyn': (40.68, -73.95),
    'Queens': (40.73, -73.85),
    'Bronx': (40.85, -73.87),
    'Staten Island': (40.58, -74.15)
}

region_pickups['Lat'] = region_pickups['Region'].map(lambda r:
region_coords.get(r, (0, 0))[0])
region_pickups['Lon'] = region_pickups['Region'].map(lambda r:
region_coords.get(r, (0, 0))[1])


plt.figure(figsize=(8, 8))
plt.scatter(
    region_pickups['Lon'],
    region_pickups['Lat'],
    s=region_pickups['Pickups'] / 50,
    alpha=0.6,
    c='dodgerblue',
    edgecolors='black'
)
for i, row in region_pickups.iterrows():
    plt.text(row['Lon'], row['Lat'],
    f"{row['Region']}\n{row['Pickups']}",
    ha='center', va='center', fontsize=10, weight='bold',
    color='white')


plt.title('Uber Pickups Across New York City Regions', fontsize=16)
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.grid(True)
plt.tight_layout()

plt.show()

