# -*- coding: utf-8 -*-
"""DAV_LAB_10_FIFA21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bgvTZs9zsm5BmqppvOf3loSiN9sSdujz
"""

!pip install squarify

import pandas as pd
import matplotlib.pyplot as plt
import squarify
import zipfile

# If your file is zipped:
with zipfile.ZipFile("/content/sample_data/players_21.csv.zip", 'r') as z:
    z.extractall()

df = pd.read_csv("/content/sample_data/players_21.csv.zip")

def map_position(pos):
    forwards = ["ST","CF","LW","RW","LF","RF"]
    mids = ["CAM","CM","CDM","LM","RM"]
    defs = ["CB","LB","RB","LWB","RWB"]

    if pos in forwards:
        return "Forward"
    elif pos in mids:
        return "Midfielder"
    elif pos in defs:
        return "Defender"
    elif pos == "GK":
        return "Goalkeeper"
    return "Other"

df["Position_Group"] = df["player_positions"].str.split(",").str[0].apply(map_position)

position_counts = df["Position_Group"].value_counts()

plt.figure(figsize=(8,4))
plt.bar(position_counts.index, position_counts.values)
plt.title("Number of Players by Position Group")
plt.xlabel("Position Group")
plt.ylabel("Number of Players")
plt.show()

bins = [0,60,70,80,90,100]
labels = ["0–60","60–70","70–80","80–90","90+"]

df["Rating_Range"] = pd.cut(df["overall"], bins=bins, labels=labels)

rating_counts = df["Rating_Range"].value_counts().sort_index()

plt.figure(figsize=(7,7))
plt.pie(rating_counts, labels=labels, autopct="%1.1f%%", startangle=90)

# Create donut hole
centre_circle = plt.Circle((0,0),0.70,fc='white')
plt.gca().add_artist(centre_circle)

plt.title("Donut Chart: Overall Rating Distribution")
plt.show()

tree_df = df.groupby("Position_Group")["overall"].mean().reset_index()

sizes = tree_df["overall"]
labels = tree_df["Position_Group"] + " (" + tree_df["overall"].round(1).astype(str) + ")"

plt.figure(figsize=(12,7))
squarify.plot(sizes=sizes, label=labels, alpha=0.9)
plt.title("Treemap: Avg Overall Rating by Player Position Group")
plt.axis("off")
plt.show()













